In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from '/usr/local/python/3.12.1/lib/python3.12/site-packages/numpy/__init__.py'>

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.full(10, 3.5)

array([3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5])

In [9]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [12]:
a[2] = 11
a

array([ 1,  2, 11,  4,  5])

In [13]:
np.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [16]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [19]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [22]:
a = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
a[2,2] = 66


In [26]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 66]])

In [28]:
a[1] = [2,2,2]
a

array([[ 1,  2,  3],
       [ 2,  2,  2],
       [ 7,  8, 66]])

In [30]:
a[:,1]

array([2, 2, 8])

In [36]:
np.random.seed(2)
100* np.random.rand(2,3)

array([[43.59949021,  2.59262318, 54.96624779],
       [43.53223926, 42.03678021, 33.0334821 ]])

In [35]:
np.random.seed(2)
np.random.randn(2,3)

array([[-0.41675785, -0.05626683, -2.1361961 ],
       [ 1.64027081, -1.79343559, -0.84174737]])

In [38]:
np.random.seed(2)
np.random.randint(low=0, high = 100, size=(5,3))

array([[40, 15, 72],
       [22, 43, 82],
       [75,  7, 34],
       [49, 95, 75],
       [85, 47, 63]])

In [45]:
a = np.array([0,1,2,3,4])
a

array([0, 1, 2, 3, 4])

In [40]:
a+1

array([1, 2, 3, 4, 5, 6])

In [41]:
a >=2

array([False, False,  True,  True,  True,  True])

In [44]:
b = np.array([0.1,0.3,4,5,6])
b

array([0.1, 0.3, 4. , 5. , 6. ])

In [48]:
a[a<b]

array([0, 2, 3, 4])

In [49]:
a > b


array([False,  True, False, False, False])

In [50]:
a.min()

np.int64(0)

In [51]:
a.max()

np.int64(4)